server:
  port: 9000
  
 #Database Configuration
spring:
  datasource:
    username: root
    password: root12345
    url: jdbc:mysql://database-1.cbgxzncrihr2.us-east-2.rds.amazonaws.com:3306/mb
    driver-class-name: com.mysql.cj.jdbc.Driver

    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    