server:
  port: 9000
  
 #Database Configuration
spring:
  datasource:
    username: root
    password: 8549996008
    url: jdbc:mysql://localhost:3306/mb
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    